---
dist: xenial
language: python

before_install:
  - openssl aes-256-cbc -K $encrypted_f8dc4e9cafc2_key -iv $encrypted_f8dc4e9cafc2_iv -in betacloud.yml.enc -out betacloud.yml -d

before_script:
  - bash scripts/prepare.sh

script:
  - bash scripts/run.sh

after_success:
  - bash scripts/export.sh
  - bash scripts/push.sh
